name: portfolio
description: "Benjamin Agardh's portfolio website"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
    
  flutter_markdown: ^0.7.5
  flutter_svg: ^2.0.17
  go_router: ^14.6.3
  google_fonts: ^6.2.1
  intl: ^0.20.1
  markdown: ^7.3.0
  timelines_plus: ^1.0.6
  url_launcher: ^6.3.1
  collection: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0
  test: ^1.25.8

  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/projects/
    - assets/me/
    - assets/contact/
    - assets/writing/
    - assets/fonts/open_sans/
